version: '3'

services:

  contracheque-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: contracheque
    ports:
      - 8080:8080
      - 5005:5005
    depends_on:
      - contracheque-mysql
    networks:
      - fk-network

  contracheque-mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=contracheque
      - MYSQL_USER=contracheque
      - MYSQL_PASSWORD=1234
    volumes:
      - erpvolume:/var/lib/mysql
    container_name: contracheque-mysql
    ports:
      - 3306:3306
    networks:
      - fk-network

volumes:
  fk-volume:

networks:
  fk-network:
    driver: bridge
