version: '3'

services:

  contracheque-mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=contracheque
      - MYSQL_USER=contracheque
      - MYSQL_PASSWORD=1234
    volumes:
      - fk-volume:/var/lib/mysql
    container_name: contracheque-mysql
    ports:
      - 3306:3306
    networks:
      - fk-network

volumes:
  fk-volume:

networks:
  fk-network:
    driver: bridge
